### ISSUE TITLE
Code License?

### ISSUE THREAD

**Issue by rds1983** [malkamius/CrimsonStainedLands#2]
What is the source code license?

**Comment by malkamius** [comment]
https://github.com/malkamius/CrimsonStainedLands/tree/main/master/CrimsonStainedLands/Licenses

Merc/Diku license possibly. Heavily based on their sources.

I don't care what you do with it, but you might want to try and abide by their requests.

**Comment by rds1983** [comment]
Thanks for the clarification.
Of course, it's up for you to decide what license to use.

But I wanted to notice that merc/diku is quite restrictive. I.e. the MUD couldn't be used for commercial purposes(even accepting donations to pay for the server hosting is forbidden). Any welcome screen should display many names from the original creator crew.

I think it would be great, if less restrictive license(such as MIT) was used.
I think it's possible to use such license if you didnt directly copy original code, but only looked at it and then wrote your own code doing similar things.

If content(areas, rooms, mobs, etc) is borrowed from diku/merc, then it might be possible to use two licenses: MIT for the code and diku/merc for the content.

**Comment by rds1983** [comment]
btw, the Diku changed their license to LGPL: https://github.com/Seifert69/DikuMUD/blob/master/dm-dist-alfa/doc/license.doc

**Comment by malkamius** [comment]
Well, if it's up to me, the code isn't copywritten at all. Some of the areas were written for Merc etc. I included the licenses from the ROM source just to be safe.

**Comment by rds1983** [comment]
Oh, great, so the code is in the public domain?
It would be great if you wrote it in the README.md. Of course, stating that some specific areas are Merc licensed.

**Comment by rds1983** [comment]
Actually, nevermind. I googled and it seems that even translating a project to different language makes it "derivative work", thus requiring to preserve the original license.
