### ISSUE TITLE
Maps for CSL

### ISSUE THREAD

**Issue by rds1983** [malkamius/CrimsonStainedLands#3]
Hello,
I am dev of [MUDMapBuilder](https://github.com/rds1983/MUDMapBuilder), which is utility to generate map images for a MUD's areas.
I've tested the utility on the CSL and generated a map for almost every area. The resulting pack of maps(122 maps) could be downloaded here: [CSL_Areas.zip](https://github.com/rds1983/MUDMapBuilder/releases/download/0.1.5/CSL_Areas.zip)
Hopefully it could be useful.

**Comment by malkamius** [comment]
Thanks, I'll check it out. Will probably upload them to the website.

**Comment by malkamius** [comment]
Your json, png files and github are linked from https://kbs-cloud.com now

There is also a mapper in the CSL repository, but it maps the whole world
and doesn't show up/down properly, just overlays rooms ordered by vnum if I
remember correctly.

I have not made that project's source code public yet.

Thanks,
Dagl/Malkamius/Christopher

**Comment by rds1983** [comment]
You welcome and thanks too!
Eventually I plan to start showing doors on those maps. Then I'll probably regenerate those images and open new issue.
