### ISSUE TITLE
Healer's THAC0

### ISSUE THREAD

**Issue by rds1983** [malkamius/CrimsonStainedLands#4]
Hello,
I've noticed that Healer's THAC0_32 is set to -10:
https://github.com/malkamius/CrimsonStainedLands/blob/11c453ea1f9455b2ef07008c9aa91519c2d0ee4d/master/CrimsonStainedLands/data/guilds.xml#L13

Which is better than everyone else THAC0_32, save warrior. Is it bug?

**Comment by malkamius** [comment]
Sure was, modified the value to match mages.
