### ISSUE TITLE
Using CSL Content in my MUD

### ISSUE THREAD

**Issue by rds1983** [malkamius/CrimsonStainedLands#5]
Hello,
I am slowly making my own [MUD engine](https://github.com/abarim-mud/AbarimMUD) and would want to use content from your MUD(areas, races, etc). As your MUD has 120+ excellent areas in human readable xml format.
Of course, I'll include all relevant licenses.
I hope you don't mind?

**Comment by malkamius** [comment]
Awesome! Let me know if I can help in any way.
